apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-root-kustomization
  namespace: flux-system
spec:
  interval: 1m
  path: ./fluxcd-examples
  prune: true
  sourceRef:
    kind: GitRepository
    name: root-git-repo
