---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: capacitor
  namespace: flux-system
spec:
  interval: 12h
  url: oci://ghcr.io/gimlet-io/capacitor-manifests
  ref:
    semver: ">=0.1.0"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: capacitor
  namespace: flux-system
spec:
  targetNamespace: flux-system
  interval: 1h
  retryInterval: 2m
  timeout: 5m
  wait: true
  prune: true
  path: "./"
  sourceRef:
    kind: OCIRepository
    name: capacitor
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: root-git-repo
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://github.com/weaveworks/weave-gitops.git
  ref:
    branch: main
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: weave-gitops
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ./charts/gitops-server
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: root-git-repo
  interval: 1m0s
  values:
    adminUser:
      create: true
      passwordHash: $2a$10$zjckuhj1rAEFnHTX.nIde.Gk8htTHbY1cjESKV937FiZmbpvoG4s.
      username: admin
---