apiVersion: v1
kind: Secret
metadata:
  name: gitea-helm-repo
  namespace: argocd-system
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://dl.gitea.com/charts/
  name: gitea
  type: helm
