apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: gitea
  namespace: argocd-system
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: 'gitea-system'
    server: '*'
  sourceRepos:
  - '*'