apiVersion: v1
kind: Secret
metadata:
  name: keycloak-helm-repo
  namespace: argocd-system
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  enableOCI: "true"
  url: registry-1.docker.io/bitnamicharts
  name: keycloak
  type: helm
