apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: keycloak
  namespace: argocd-system
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: 'keycloak-system'
    server: '*'
  sourceRepos:
  - '*'