apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: root
  namespace: argocd-system
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - name: '*'
    namespace: '*'
    server: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - https://github.com/hamdikh/gitops-examples.git