apiVersion: v1
kind: Secret
metadata:
  name: root-git-repo
  namespace: argocd-system
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  insecure: "true"
  project: root
  url: "https://github.com/hamdikh/gitops-examples.git"
  type: git


